@startuml "domain_modeling"

title "Shop example Domain Modeling"

skinparam componentStyle rectangle

component Member
component Order
component Delivery
component OrderItem
component Item
component Category
component Album
component Book
component Movie

Member "1" -down- "*" Order
Order "1" -down- "1" Delivery

Order "1" -right- "*" OrderItem
OrderItem "*" -right- "1" Item

Category "*" -down- "*" Item

Item <|-down- Album
Item <|-down- Book
Item <|-down- Movie

@endum